# turn on unstable features
edition = "2021"
unstable_features = true

brace_style = "PreferSameLine"
fn_single_line = true
format_macro_matchers = true
format_strings = true
force_explicit_abi = false
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
match_arm_blocks = false
match_block_trailing_comma = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
